"""
Import fixtures from a CSV generated by generate_fixture_csv.

CSV columns: competition, season, home_team, away_team,
             kickoff, home_score, away_score, status, matchday

Usage:
    uv run python manage.py import_csv_fixtures fixtures_backfill.csv
    uv run python manage.py import_csv_fixtures fixtures_backfill.csv --dry-run
"""

import csv
import hashlib
from datetime import datetime, timedelta, timezone

from django.core.management.base import BaseCommand

from grounds.models import Match, Team

NAME_OVERRIDES = {
    # football-data.co.uk short name -> our Team.name (reviewed & approved 2026-06)
    "Preston": "Preston North End",
    "Plymouth": "Plymouth Argyle",
    "Rotherham": "Rotherham United",
    "Peterboro": "Peterborough United",
    "Crewe": "Crewe Alexandra",
    "Swindon": "Swindon Town",
    "Cardiff": "Cardiff City",
    "Huddersfield": "Huddersfield Town",
    "Wycombe": "Wycombe Wanderers",
    "Northampton": "Northampton Town",
    "Colchester": "Colchester United",
    "Bradford": "Bradford City",
    "Hull": "Hull City",
    "QPR": "Queens Park Rangers",
    "Ipswich": "Ipswich Town",
    "Sheffield Weds": "Sheffield Wednesday",
    "Swansea": "Swansea City",
    "Birmingham": "Birmingham City",
    "Derby": "Derby County",
    "Bristol Rvs": "Bristol Rovers",
    "Nott'm Forest": "Nottingham Forest",
    "Shrewsbury": "Shrewsbury Town",
    "Charlton": "Charlton Athletic",
    "Norwich": "Norwich City",
    "Coventry": "Coventry City",
    "Brighton": "Brighton & Hove Albion",
    "Brighton and Hove Albion": "Brighton & Hove Albion",  # TheSportsDB spelling
    "Bournemouth": "AFC Bournemouth",
    "Wigan": "Wigan Athletic",
    "Stoke": "Stoke City",
    "Wolves": "Wolverhampton Wanderers",
    "West Brom": "West Bromwich Albion",
    "Carlisle": "Carlisle United",
    "Leeds": "Leeds United",
    "Bolton": "Bolton Wanderers",
    "Blackburn": "Blackburn Rovers",
    "Leicester": "Leicester City",
    "Tranmere": "Tranmere Rovers",
    "Oldham": "Oldham Athletic",
    "Oxford": "Oxford United",
    "Man City": "Manchester City",
    "West Ham": "West Ham United",
    "Luton": "Luton Town",
    "Newcastle": "Newcastle United",
    "Exeter": "Exeter City",
    "Mansfield": "Mansfield Town",
    "Doncaster": "Doncaster Rovers",
    "Tottenham": "Tottenham Hotspur",
    "Man United": "Manchester United",
    "Lincoln": "Lincoln City",
    "Grimsby": "Grimsby Town",
    "Cheltenham": "Cheltenham Town",
    "Cambridge": "Cambridge United",
    "Stockport": "Stockport County",
    "Milton Keynes Dons": "MK Dons",
    "Accrington": "Accrington Stanley",
    "Burton": "Burton Albion",
    "York": "York City",
    "Salford": "Salford City",
    "Forest Green": "Forest Green Rovers",
    "Harrogate": "Harrogate Town",
    "Boston": "Boston United",
    # Non-92 clubs seeded by seed_result_clubs (Team + Ground). They appear as
    # opponents in historical results so must resolve here. "Wimbledon" = the
    # ORIGINAL Wimbledon FC (-> MK Dons 2004), seeded as "Wimbledon FC" and kept
    # distinct from AFC Wimbledon. (Bury/Darlington/Scarborough match by exact
    # name and need no override.)
    "Scunthorpe": "Scunthorpe United",
    "Southend": "Southend United",
    "Hartlepool": "Hartlepool United",
    "Torquay": "Torquay United",
    "Macclesfield": "Macclesfield Town",
    "Yeovil": "Yeovil Town",
    "Wimbledon": "Wimbledon FC",
    "Dag and Red": "Dagenham & Redbridge",
    "Kidderminster": "Kidderminster Harriers",
    "Rushden & D": "Rushden & Diamonds",
    "Aldershot": "Aldershot Town",
    "Halifax": "Halifax Town",
    "Sutton": "Sutton United",
}


def _build_team_map():
    """Build a case-insensitive name → Team map, stripping common suffixes."""
    team_map = {}
    for team in Team.objects.select_related("ground"):
        names = {team.name}
        for suffix in (" FC", " AFC", " F.C.", " A.F.C."):
            stripped = team.name.replace(suffix, "").strip()
            names.add(stripped)
        for n in names:
            team_map[n.lower()] = team
    return team_map


def _find_team(name, team_map):
    if name in NAME_OVERRIDES:
        name = NAME_OVERRIDES[name]
    # Try exact lowercase first
    lower = name.lower()
    if lower in team_map:
        return team_map[lower]
    # Try stripping common suffixes
    for suffix in (" fc", " afc", " f.c.", " a.f.c."):
        candidate = lower.removesuffix(suffix).strip()
        if candidate in team_map:
            return team_map[candidate]
    return None


def _synthetic_external_id(competition, kickoff_str, home_name, away_name):
    """Stable integer ID for synthetic matches that won't clash with real API IDs.

    Keyed on the match *date* (not the full timestamp) so the same fixture
    imported with a different kick-off time resolves to one record.
    """
    key = f"csv:{competition}:{kickoff_str}:{home_name}:{away_name}"
    digest = hashlib.md5(key.encode()).hexdigest()[:10]
    return 900_000_000 + int(digest, 16) % 99_000_000


class Command(BaseCommand):
    help = "Import fixtures from a CSV file into the Match model"

    def add_arguments(self, parser):
        parser.add_argument("csv_file", type=str, help="Path to the CSV file")
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Report what would be imported without writing to the DB",
        )

    def handle(self, *args, **options):
        csv_file = options["csv_file"]
        dry_run = options["dry_run"]
        team_map = _build_team_map()

        created = updated = skipped = 0
        unmatched_names: set[str] = set()
        # Track assigned external_ids so synthetic-id hash collisions (the id
        # space is narrower than the row count) resolve to a free integer.
        used_ids: set[int] = set(Match.objects.values_list("external_id", flat=True))

        with open(csv_file, newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                home = _find_team(row["home_team"], team_map)
                away = _find_team(row["away_team"], team_map)

                if not home:
                    unmatched_names.add(row["home_team"])
                if not away:
                    unmatched_names.add(row["away_team"])
                if not home or not away:
                    skipped += 1
                    continue

                kickoff_str = row["kickoff"]
                try:
                    kickoff = datetime.fromisoformat(kickoff_str.replace("Z", "+00:00"))
                    if kickoff.tzinfo is None:
                        kickoff = kickoff.replace(tzinfo=timezone.utc)
                except ValueError:
                    self.stderr.write(f"  Bad kickoff: {kickoff_str}")
                    skipped += 1
                    continue

                competition = row.get("competition", "PL").strip()
                status = row.get("status", "FINISHED").strip() or "FINISHED"

                hs_raw = row.get("home_score", "").strip()
                as_raw = row.get("away_score", "").strip()
                home_score = int(hs_raw) if hs_raw != "" else None
                away_score = int(as_raw) if as_raw != "" else None

                matchday_raw = row.get("matchday", "").strip()
                matchday = int(matchday_raw) if matchday_raw else None

                ground = getattr(home, "ground", None)

                if dry_run:
                    self.stdout.write(
                        f"  [{competition}] {home.name} v {away.name}  "
                        f"{kickoff.date()}  {home_score}-{away_score}"
                    )
                    created += 1
                    continue

                # Idempotent upsert on the natural key (teams + competition +
                # date). This matches any record from a prior API/backfill import
                # regardless of its external_id or stored kick-off time, so the
                # same fixture is never duplicated. A +/-5 day window absorbs date
                # disagreements between sources (postponements, COVID reschedules);
                # the same home pairing never recurs within a season, so the
                # window can't merge two genuinely distinct fixtures.
                existing = Match.objects.filter(
                    home_team=home,
                    away_team=away,
                    competition=competition,
                    kickoff__gte=kickoff - timedelta(days=5),
                    kickoff__lte=kickoff + timedelta(days=5),
                ).first()

                if existing:
                    existing.home_score = home_score
                    existing.away_score = away_score
                    existing.status = status
                    if existing.ground_id is None:
                        existing.ground = ground
                    if matchday is not None:
                        existing.matchday = matchday
                    # Preserve an existing real kick-off time; only fill it in if
                    # the stored time is the placeholder default (15:00).
                    if existing.kickoff.timetuple()[3:5] == (15, 0):
                        existing.kickoff = kickoff
                    existing.save()
                    updated += 1
                else:
                    ext_id = _synthetic_external_id(
                        competition, kickoff.date().isoformat(), home.name, away.name
                    )
                    while ext_id in used_ids:  # resolve hash collision
                        ext_id += 1
                    used_ids.add(ext_id)
                    Match.objects.create(
                        external_id=ext_id,
                        home_team=home,
                        away_team=away,
                        ground=ground,
                        kickoff=kickoff,
                        competition=competition,
                        matchday=matchday,
                        status=status,
                        home_score=home_score,
                        away_score=away_score,
                    )
                    created += 1

        if unmatched_names:
            self.stdout.write(self.style.WARNING(
                f"\nUnmatched team names ({len(unmatched_names)}) — "
                "add to NAME_OVERRIDES in this command if needed:"
            ))
            for n in sorted(unmatched_names):
                self.stdout.write(f"  {n!r}")

        verb = "Would import" if dry_run else "Done"
        self.stdout.write(self.style.SUCCESS(
            f"\n{verb}: {created} created, {updated} updated, {skipped} skipped"
        ))
