# Generated by Django 6.0.4 on 2026-04-30 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('league_level', models.CharField(choices=[('premier-league', 'Premier League'), ('championship', 'Championship'), ('league-one', 'League One'), ('league-two', 'League Two'), ('non-league', 'Non-League'), ('scotland', 'Scotland'), ('wales', 'Wales'), ('international', 'International'), ('other', 'Other')], default='other', max_length=40)),
                ('is_current_92', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, upload_to='team-logos/')),
                ('primary_colour', models.CharField(default='#19704B', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('town_or_city', models.CharField(max_length=120)),
                ('address', models.TextField(blank=True)),
                ('postcode', models.CharField(blank=True, max_length=12)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('opened_year', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='grounds/')),
                ('away_allocation', models.PositiveIntegerField(blank=True, null=True)),
                ('away_entrance', models.CharField(blank=True, max_length=160)),
                ('parking_notes', models.TextField(blank=True)),
                ('drinking_notes', models.TextField(blank=True)),
                ('transport_notes', models.TextField(blank=True)),
                ('first_visit_tip', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ground', to='grounds.team')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
