# Generated by Django 6.0.4 on 2026-06-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grounds", "0003_add_lat_lng_to_ground"),
    ]

    operations = [
        migrations.AddField(
            model_name="ground",
            name="away_end",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
