# Generated by Django 6.0.4 on 2026-06-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grounds", "0004_add_away_end_to_ground"),
    ]

    operations = [
        migrations.AddField(
            model_name="ground",
            name="info_updated_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="shirt",
            field=models.ImageField(blank=True, upload_to="team-shirts/"),
        ),
    ]
