# Generated by Django 6.0.4 on 2026-06-12 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grounds", "0006_add_suggestion_and_tip_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.IntegerField(unique=True)),
                ("kickoff", models.DateTimeField()),
                ("competition", models.CharField(default="PL", max_length=10)),
                ("matchday", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("TIMED", "Timed"),
                            ("IN_PLAY", "In Play"),
                            ("PAUSED", "Paused"),
                            ("FINISHED", "Finished"),
                            ("POSTPONED", "Postponed"),
                            ("CANCELLED", "Cancelled"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("home_score", models.PositiveIntegerField(blank=True, null=True)),
                ("away_score", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "away_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="away_matches",
                        to="grounds.team",
                    ),
                ),
                (
                    "ground",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches",
                        to="grounds.ground",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_matches",
                        to="grounds.team",
                    ),
                ),
            ],
            options={
                "ordering": ["kickoff"],
            },
        ),
        migrations.AddField(
            model_name="visit",
            name="match",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visits",
                to="grounds.match",
            ),
        ),
    ]
