# Generated by Django 6.0.4 on 2026-06-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grounds", "0008_ground_editors_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="groundsuggestion",
            name="proposed_image",
            field=models.ImageField(blank=True, upload_to="suggestions/"),
        ),
        migrations.AlterField(
            model_name="groundsuggestion",
            name="field_name",
            field=models.CharField(
                choices=[
                    ("image", "Ground photo"),
                    ("parking_notes", "Where to park"),
                    ("drinking_notes", "Where to drink"),
                    ("transport_notes", "Getting there"),
                    ("away_end", "Away end"),
                    ("away_entrance", "Away entrance"),
                    ("away_allocation", "Away allocation"),
                    ("first_visit_tip", "First visit tip"),
                    ("capacity", "Capacity"),
                    ("opened_year", "Opened year"),
                    ("address", "Address"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="groundsuggestion",
            name="proposed_value",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
