# Generated by Django 6.0.4 on 2026-07-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grounds", "0009_groundsuggestion_proposed_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="logo",
        ),
    ]
